<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Comic;

class ComicSeeder extends Seeder
{
    public function run()
    {
        Comic::create([
            'title' => 'Invincible',
            'description' => 'Mark Grayson is a normal high school freshman whose father, Nolan Grayson, is an extraterrestrial of the planet Viltrum known as Omni-Man, the most powerful superhero on the planet. At age seventeen, Mark begins to display super powers as a result of his Viltrumite ancestry, and adopts the superhero name Invincible with his father acting as his mentor. Early in his hero career Mark meets heroine Atom Eve, and they eventually enter a relationship. Mark begins as a small-time hero solving problems and fighting low-level crime around his school. 
                                However, the scope of his adventures quickly progresses to national, global, intergalactic, and multidimensional. Large portions of the narrative focus on conflict with the fascistic multiplanetary Viltrum Empire, which Mark participates in a rebellion against. Multiple points of view, and the power struggles therein, factor heavily into the comic. Characters often have motives that do not align, and commonly swap between conventional "hero" and "villain" roles as a result. Most notably, Mark\'s father Omni-Man begins the series as an antagonist and is eventually reformed through Mark\'s efforts, which Mark continues to attempt on other enemies. 
                                Mark himself vacillates between working for and against the United States government, and often breaks from the consensus of his friends and allies to pursue what he sees as the optimal and/or pragmatic choice.',
            'comment_count' => 5,
            'image_path' => 'images/invincible-comic2.jpeg'
        ]);

        Comic::create([
            'title' => 'The Walking Dead',
            'description' => 'The Walking Dead is an American post-apocalyptic comic book series created by writer Robert Kirkman and artist Tony Moore – who was the artist on the first six issues and cover artist for the first twenty-four – with art on the remainder of the series by Charlie Adlard. Beginning in 2003 and published by Image Comics, the series ran for 193 issues, with Kirkman unexpectedly ending the series in 2019. Apart from a few specials, the comic was published primarily in black and white. 
                                It began publishing colorized versions issue by issue, colored by Dave McCaig, starting in October 2020. The comic book series focuses on Rick Grimes, a Kentucky deputy who is shot in the line of duty and awakens from a coma in a zombie apocalypse that has resulted in a state-wide quarantine. After joining with some other survivors, he gradually takes on the role of leader of a community as it struggles to survive the zombie apocalypse. The Walking Dead received the 2007 and 2010 Eisner Award for Best Continuing Series at San Diego Comic-Con. 
                                The AMC television series The Walking Dead (2010–2022) loosely follows the storyline of the comic book. The Walking Dead franchise has also spawned multiple additional media properties, including four companion television series (the first two of which were Fear the Walking Dead and The Walking Dead: World Beyond), eight webisode series, video games (starting with The Walking Dead: The Game), and various additional publications, including novels (starting with The Walking Dead: Rise of the Governor).',
            'comment_count' => 3,
            'image_path' => 'images/walking-dead-comic1.jpeg'
        ]);

        Comic::create([
            'title' => 'Watchmen',
            'description' => 'Watchmen is a comic book limited series by the British creative team of writer Alan Moore, artist Dave Gibbons, and colorist John Higgins. It was published monthly by DC Comics in 1986 and 1987 before being collected in a single-volume edition in 1987. Watchmen originated from a story proposal Moore submitted to DC featuring superhero characters that the company had acquired from Charlton Comics. 
                                As Moore\'s proposed story would have left many of the characters unusable for future stories, managing editor Dick Giordano convinced Moore to create original characters instead. Moore used the story as a means of reflecting contemporary anxieties, deconstructing and satirizing the superhero concept, and making political commentary. Watchmen depicts an alternate history in which superheroes emerged in the 1940s and 1960s and their presence changed history so that the United States won the Vietnam War and the Watergate scandal was never exposed. 
                                In 1985, the country is edging toward World War III with the Soviet Union, freelance costumed vigilantes have been outlawed and most former superheroes are in retirement or working for the government. The story focuses on the protagonists\' personal development and moral struggles as an investigation into the murder of a government-sponsored superhero pulls them out of retirement. Gibbons uses a nine-panel grid layout throughout the series and adds recurring symbols such as a blood-stained smiley face. 
                                All but the last issue feature supplemental fictional documents that add to the series\' backstory and the narrative is intertwined with that of another story, an in-story pirate comic titled Tales of the Black Freighter, which one of the characters reads. Structured at times as a nonlinear narrative, the story skips through space, time, and plot. In the same manner, entire scenes and dialogues have parallels with others through synchronicity, coincidence, and repeated imagery. 
                                A commercial success, Watchmen has received critical acclaim both in the comics and mainstream press. Watchmen was recognized in Time\'s List of the 100 Best Novels as one of the best English language novels published since 1923. In a retrospective review, the BBC\'s Nicholas Barber described it as "the moment comic books grew up". Moore opposed this idea, stating, "I tend to think that, no, comics hadn\'t grown up. There were a few titles that were more adult than people were used to. 
                                But the majority of comics titles were pretty much the same as they\'d ever been. It wasn\'t comics growing up. I think it was more comics meeting the emotional age of the audience coming the other way.\" After several attempts to adapt the series into a feature film, director Zack Snyder\'s Watchmen was released in 2009. An episodic video game, Watchmen: The End Is Nigh, was released to coincide with the film\'s release. DC Comics published Before Watchmen, a series of nine prequel miniseries, in 2012, and Doomsday Clock, a 12-issue limited series and sequel to the original Watchmen series, from 2017 to 2019 – both without Moore\'s or Gibbons\' involvement. 
                                The second series integrated the Watchmen characters within the DC Universe. A standalone sequel, Rorschach by Tom King, began publication in October 2020. A television continuation to the original comic, set 34 years after the comic\'s timeline, was broadcast on HBO from October to December 2019 with Gibbons\' involvement. Moore has expressed his displeasure with adaptations and sequels of Watchmen and asked it not be used for future works.',
            'comment_count' => 9,
            'image_path' => 'images/watchmen-comic1.jpeg'
        ]);

        Comic::create([
            'title' => 'Marvel\'s Civil War',
            'description' => 'The New Warriors (Night Thrasher, Namorita, Speedball, and Microbe) battle a group of villains (Cobalt Man, Speedfreek, Coldheart, and Nitro) in Stamford, Connecticut, while filming a reality television show. Nitro explodes, killing more than 600 people (including school children and every villain and New Warrior present, minus Speedball). Numerous other superheroes appear in Stamford to search for survivors. Public opinion turns against superhumans, branding even inactive members of the New Warriors as "baby killers". Hindsight, desperate to distance himself from the team, releases the New Warriors\' secret identities online, and several of them are attacked. She-Hulk forces Hindsight to shut down the site, and Hindsight is arrested by John Jameson. Angry civilians attack the Human Torch outside a club after he cuts the line and mocks one of his critics.
                                Guided by Iron Man, Congress passes the Superhuman Registration Act (SHRA), requiring the registration of all persons with superhuman abilities with the U.S. government, and the enlistment and training of all aspiring superheroes. The law applies to those with naturally-occurring superhuman abilities, humans using exotic technology (e.g. Iron Man), or anyone who wants to challenge superhumans. Enactment of the federal law leads to revisions of state criminal codes. Characters within the Marvel Universe superhero community split into two groups. One advocates registration as a responsible obligation, and the other opposes it, arguing the act violates civil liberties and the protection secret identities provide. While arguing with Iron Man about the law, African American hero Luke Cage compares the mandatory registration to slavery. A number of villains also choose a side.
                                Captain America refuses to join a S.H.I.E.L.D. strike force hunting violators of the act, and is attacked by S.H.I.E.L.D.\'s "Cape-Killers" before the act is even passed. He subsequently becomes a fugitive, and forms an underground resistance movement calling itself the "Secret Avengers". This team includes Hercules, Falcon, Danny Rand (who is acting as Daredevil in Matt Murdock\'s place), Luke Cage, and the Young Avengers. Iron Man, Reed Richards, Hank Pym (actually a Skrull in disguise), and She-Hulk come down in favor of the act. Spider-Man unmasks at a press conference as a show of support for the act. Doctor Strange wants no part of the act and tells Iron Man and Mister Fantastic to never call on him again (the government subsequently declares Doctor Strange exempt).
                                The government-backed heroes track down unregistered superhumans and subsequently detain or register them. Captain America\'s Secret Avengers and Iron Man\'s Avengers end up fighting in Yancy Street. The Thing, who was only visiting his old neighborhood, gets roped into crowd control. However, when a young member of the Yancy Street Gang is killed in the ensuing violence, he leaves the country for France. The Secret Avengers, responding to a false emergency, are lured into an ambush by the pro-registration forces. As the battle turns against them, a new weapon is brought into play: Project Lightning, a cyborg clone of Thor. Confronted by Bill Foster, "Thor" sends a bolt of lightning through his chest, killing him. With both sides stunned, Cap orders a retreat. Sue Storm shelters the re-grouping Secret Avengers under an energy shield, allowing their escape.',
            'comment_count' => 7,
            'image_path' => 'images/marvel-comic1.jpeg'
        ]);

        Comic::create([
            'title' => 'Tech Jacket',
            'description' => 'Zack Thompson, a high school kid, finds a dying alien from a race of incredibly intelligent but physically weak beings called the Geldarians. To make up for this they have invented the Tech Jacket, a vest that every Geldarian is equipped with upon birth. Seeing the human and knowing his crashed spaceship is going to blow up and kill them both, the alien fits him with the Tech Jacket, saving his life. But now the Tech Jacket can\'t be removed and gives Zack "one of the most powerful weapons in the universe". After saving his father (who is therefore aware of the Tech Jacket), Zack tells him about the crashed spaceship and dying alien. Later, the Geldarians show up, thinking Zack killed their comrade Kelda (the alien) and stole the Tech Jacket. After helping the Geldarians fight the Kresh, the Geldarians felt grateful towards him.
                                He appeared in Invincible 71, working on a space station with his father. The station was implied to have been built by him. According to a conversation he had with Allen the Alien, he mainly involves himself in galactic events, and calls himself a "galactic guardian" instead of a superhero. He was recruited by Allen and Nolan to accompany them to fight against the Viltrumites. While on board a spaceship with Invincible, they were attacked by Conquest and two additional Viltrumites.',
            'comment_count' => 12,
            'image_path' => 'images/tech-jacket-comic1.jpeg'
        ]);

        Comic::create([
            'title' => 'Injustice',
            'description' => 'Year One features the Insurgency led by Batman against the Justice League led by Superman and the establishment of the One Earth Regime.
                                In Metropolis, a pregnant Lois Lane is kidnapped by Joker. While Superman searches for her, Batman and the Justice League deduce that Joker has used Scarecrow\'s fear toxin and laced it with stolen kryptonite to affect Superman. Superman and the League track Lois to a submarine where Joker and Harley Quinn are hiding, but Superman is attacked by Doomsday. He fights and defeats Doomsday, only to learn Doomsday is an illusion, and he has been fighting an unconscious Lois. Too late, he learns that Lois\'s heart was synced to a nuclear warhead, which detonates and destroys Metropolis when her heart stops. Blinded by grief and revenge, Superman kills Joker despite Green Lantern\'s and Batman\'s efforts to stop him.
                                A grieving Superman decides that all violence must end, by force if necessary. He addresses the United Nations, with Wonder Woman beside him, revealing his secret identity and demanding an immediate cessation of all worldwide hostilities. In response, the United States government contracts Mirror Master to kidnap Jonathan and Martha Kent to use as leverage against Superman. Using increasingly draconian measures, the League locates Mirror Master, and Superman relocates his parents to the Fortress of Solitude. The global escalation continues, with Wonder Woman becoming Superman\'s advisor as the League stops conflicts by force. Batman and Superman grow increasingly at odds, with Batman questioning Superman\'s and the League\'s methods.
                                In the Pacific Ocean, the League responds to a whaling ship under attack by Aquaman at the head of an Atlantean army. Tensions boil over into a full-scale battle until Superman coerces Aquaman into backing down, but not before Atlantean armies appear on multiple coastlines as a reminder of Atlantis\'s power. In response, Superman lifts Atlantis and places it in the Sahara Desert. Aquaman backs down, telling Wonder Woman that he is willing to advise Superman as a fellow ruler, but she does not relay the message. In Australia, Superman and Wonder Woman violently respond to a public demonstration against the League\'s new tactics, crippling a fan and wannabe hero named Galaxor. The Flash, also present, begins to doubt the League\'s mission.
                                Following the destruction of Metropolis, Harley Quinn escapes police custody but is recaptured by Green Arrow. He takes her to Arkham Asylum, where Superman, Wonder Woman, and Cyborg have also arrived to relocate the inmates to parts unknown. Batman and Nightwing arrive to stop them, but Robin (who believes in Superman\'s new crusade) switches sides to join Superman. In the ensuing fight, Robin accidentally kills Nightwing, the shock of which ends all hostilities.
                                At Superman\'s private urging, Catwoman goes to Wayne Manor to console Bruce Wayne. She and Batman secretly meet with the President, who asks Batman to neutralize Superman. He begins building a team to oppose Superman\'s League—including Catwoman, Green Arrow, Aquaman, Black Canary, Black Lightning, Huntress, Captain Atom, and Batwoman. With the battle lines drawn, Superman\'s League continues its mission of stopping conflicts by force. Shazam forces Black Adam to give up his power but begins to doubt Superman\'s mission as a result.
                                Lex Luthor is found as the lone survivor in the ruins of Metropolis. He meets with Superman\'s League and wishes to join them, promising to recruit more members to Superman\'s side. Meanwhile, Batman\'s League kidnaps Hawkgirl and replaces her with Martian Manhunter, thereby gaining a spy in Superman\'s League.',
            'comment_count' => 21,
            'image_path' => 'images/dc-comic1.jpg'
        ]);
    }
}

